In [1]:
import pandas as pd
import numpy as np

# Introduction to Pandas Objects


## 1) The Pandas Series Object

In [2]:
data = [1,2,3,4,5,6]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [3]:
#indexing the series 
series.index = ['a','b','c','d','e','f']
print(series)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64


In [4]:
series.values # gives the values of the series

array([1, 2, 3, 4, 5, 6])

In [5]:
series.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [6]:
series.dtype

dtype('int64')

 # Accessing data in Series
 data can be accessed by the associated index via the familiar
Python square-bracket notation:

In [7]:
series[1]

2

In [8]:
series.iloc[0:2]

a    1
b    2
dtype: int64

In [9]:
series[0:3]

a    1
b    2
c    3
dtype: int64

In [10]:
series[::-1] # reverse the given series

f    6
e    5
d    4
c    3
b    2
a    1
dtype: int64

In [11]:
#we can access the element of the series using the index as follow
series.loc['a']

1

### Series as specialized dictionary

In [12]:
#let's create the players dictionary first 
players = {'Warner': 179, 'Smith': 164, 'Maxwell': 102, 'Finch':153, 'Stonis': 145}
# pass the players dictionary to the series
data = pd.Series(players)

In [13]:
data

Warner     179
Smith      164
Maxwell    102
Finch      153
Stonis     145
dtype: int64

In [14]:
data.index

Index(['Warner', 'Smith', 'Maxwell', 'Finch', 'Stonis'], dtype='object')

In [15]:
data.name = 'Highest ODI Score'

In [16]:
data

Warner     179
Smith      164
Maxwell    102
Finch      153
Stonis     145
Name: Highest ODI Score, dtype: int64

In [17]:
data.loc['Warner']

179

In [18]:
data['Smith']

164

## 2) The Pandas DataFrame Object

# DataFrame as a generalized NumPy array
If a Series is an analog of a one-dimensional array with flexible indices, a DataFrame
is an analog of a two-dimensional array with both flexible row indices and flexible
column names. You can think of a DataFrame as a
sequence of aligned Series objects.

In [19]:
dictionary = {'a':1,'b':2,'c':3,'d':4,'e':5} # key is the index in the series and data frame
series = pd.Series(dictionary)

In [20]:
series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [21]:
dataFrame = pd.DataFrame({'numbers':series, 'binary':[1,10,11,100,101]})

In [22]:
dataFrame

numbers  binary
a        1       1
b        2      10
c        3      11
d        4     100
e        5     101

In [23]:
dataFrame.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [24]:
dataFrame.columns

Index(['numbers', 'binary'], dtype='object')

In [25]:
dataFrame.loc['a':, 'binary':] # accessing rows and columns using loc 

binary
a       1
b      10
c      11
d     100
e     101

In [26]:
dataFrame.iloc[:3,:1] # accessing rows and columns using iloc

numbers
a        1
b        2
c        3

In [27]:
dataFrame.loc[['a','b','d']] # accessing using lists of index 

numbers  binary
a        1       1
b        2      10
d        4     100

In [28]:
dataFrame.loc['a'].values

array([1, 1])

#### From a list of dicts.

In [29]:
lists = [{'a':i,'b':i ** 2} for i in range(10)] #list comprehension

In [30]:
lists

[{'a': 0, 'b': 0},
 {'a': 1, 'b': 1},
 {'a': 2, 'b': 4},
 {'a': 3, 'b': 9},
 {'a': 4, 'b': 16},
 {'a': 5, 'b': 25},
 {'a': 6, 'b': 36},
 {'a': 7, 'b': 49},
 {'a': 8, 'b': 64},
 {'a': 9, 'b': 81}]

In [31]:
pd.DataFrame(lists).head(3)

a  b
0  0  0
1  1  1
2  2  4

Even if some keys in the dictionary are missing, Pandas will fill them in with NaN (i.e.,
“not a number”) values:

In [32]:
pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [33]:
pd.DataFrame([{'a':1,'b':3},{'c':3,'d':4}]) # first dictionary is  first row and second dic as second row

a    b    c    d
0  1.0  3.0  NaN  NaN
1  NaN  NaN  3.0  4.0

#### From a two-dimensional NumPy array

In [34]:
a = np.arange(4).reshape(2,2)

In [35]:
data = pd.DataFrame(a,columns = ['a','b'],index = ['1','2'])

In [36]:
data

a  b
1  0  1
2  2  3

## 3) The Pandas Index Object
Pandas Index object are immutable

In [37]:
Index_Object = pd.Index([1,2,3,4,5,6])

In [38]:
Index_Object

Int64Index([1, 2, 3, 4, 5, 6], dtype='int64')

In [39]:
Index_Object[1]

2

In [40]:
# Index_Object[1] = 3 # index doesn't support mutable operation

### Data Selection in DataFrame

In [41]:
# here key of the dictionary act as the index 
# DataFrame can be constructed using Pandas Series object
area = pd.Series({'California': 423967, 'Texas': 695662,
'New York': 141297, 'Florida': 170312,
'Illinois': 149995}) # area 
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127, 'Florida': 19552860,
'Illinois': 12882135}) # population
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [42]:
# to swap rows and columns of the data
data.T

California     Texas  New York   Florida  Illinois
area      423967    695662    141297    170312    149995
pop     38332521  26448193  19651127  19552860  12882135

##### The individual Series that make up the columns of the DataFrame can be accessed

In [43]:
data['area'] 

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [44]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [45]:
data.area is data['area']

True

#### Adding new column 

In [46]:
data['Density'] = data['pop'] / data['area']

In [47]:
data.head()

area       pop     Density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

DataFrame as two-dimensional array

In [48]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [49]:
a = np.arange(1,10).reshape(3,-1)
new_dataFrame = pd.DataFrame(a)

In [50]:
new_dataFrame.head()

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## Data Indexing and Selection

In [51]:
series = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['a', 'b', 'c', 'd'])

In [52]:
series

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

Like a dictionary, the Series object provides a mapping from a collection of keys to a
collection of values:

In [53]:
'a' in series

True

In [54]:
series['a']

0.25

In [55]:
series.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [56]:
list(series.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [57]:
# series object can be modified like dictionary 
series['a'] = 99
series

a    99.00
b     0.50
c     0.75
d     1.00
dtype: float64

### slicing series using explicit and implict index

during explicit index slicing final index is also included but during implicit slicing final index is excluded

In [58]:
#slicing by using explicit index
series['a':'c']

a    99.00
b     0.50
c     0.75
dtype: float64

In [59]:
# slicing by implicit index
series[0:3]

a    99.00
b     0.50
c     0.75
dtype: float64

masking and fancy indexing

In [60]:
#masking is also known as boolean indexing
mask = (series < 9)
series[mask]

b    0.50
c    0.75
d    1.00
dtype: float64

In [61]:
fancy_index = ['a','c'] # we even can pass list to slice the series
series[fancy_index]

a    99.00
c     0.75
dtype: float64

# indexer ( iloc loc ix )

if your Series has an explicit integer index, an indexing operation such as data[1] will
use the explicit indices, while a slicing operation like data[1:3] will use the implicit
Python-style index.

In [62]:
series = pd.Series(np.arange(1,10), index = np.arange(9,0,-1))

In [63]:
series

9    1
8    2
7    3
6    4
5    5
4    6
3    7
2    8
1    9
dtype: int64

In [64]:
series[9] #explicit indexing

1

In [65]:
# but slicing use implicit indexing
series[0:3]

9    1
8    2
7    3
dtype: int64

So this could be the source of confusion. Pandas provides
some special indexer attributes that explicitly expose certain indexing schemes 

## loc
the loc attribute allows indexing and slicing that always references the explicit
index:

In [66]:
series

9    1
8    2
7    3
6    4
5    5
4    6
3    7
2    8
1    9
dtype: int64

In [67]:
series.loc[9:4] # during explicit indexing final index is also included

9    1
8    2
7    3
6    4
5    5
4    6
dtype: int64

In [68]:
series.loc[1]

9

## iloc
The iloc attribute allows indexing and slicing that always references the implicit
Python-style index:

In [69]:
series

9    1
8    2
7    3
6    4
5    5
4    6
3    7
2    8
1    9
dtype: int64

In [70]:
series.iloc[1:5] # final index is excluded like in python indexing

8    2
7    3
6    4
5    5
dtype: int64

In [71]:
series.iloc[1]

2

In [72]:
series.iloc[1] is series.loc[1] # 2 not equal to 9

False

# Data Selection in DataFrame
DataFrame acts as two dimensional array

Data Frame as dictionary

In [73]:
a = {'a':100,'b':122,'c':87,'d':94,'e':115}
b = {'a':97,'b':98,'c':99,'d':100,'e':101}

In [74]:
data = pd.DataFrame({'length':a,'breadth':b})

In [75]:
data

length  breadth
a     100       97
b     122       98
c      87       99
d      94      100
e     115      101

In [76]:
# The individual Series that make up the columns of the DataFrame can be accessed
# via dictionary-style indexing of the column name

data['length'] # or data.length

a    100
b    122
c     87
d     94
e    115
Name: length, dtype: int64

In [77]:
data['length'] is data.length

True

### Adding new column in DataFrame

In [78]:
data

length  breadth
a     100       97
b     122       98
c      87       99
d      94      100
e     115      101

In [79]:
# lets add two new column name area and perimeter for rectangle
data['periemeter'] = 2*(data['length'] + data.breadth)
data['area'] = data.length * data.breadth

In [80]:
data.head(3)

length  breadth  periemeter   area
a     100       97         394   9700
b     122       98         440  11956
c      87       99         372   8613

In [81]:
# lets change the index of the data
data.set_index(np.arange(5),inplace = True)

In [82]:
data

length  breadth  periemeter   area
0     100       97         394   9700
1     122       98         440  11956
2      87       99         372   8613
3      94      100         388   9400
4     115      101         432  11615

## DataFrame as two-dimensional array

In [83]:
data.shape

(5, 4)

In [84]:
data.values

array([[  100,    97,   394,  9700],
       [  122,    98,   440, 11956],
       [   87,    99,   372,  8613],
       [   94,   100,   388,  9400],
       [  115,   101,   432, 11615]])

In [85]:
# lets swap rows and column of the data using transpose property of matrix
data.T

0      1     2     3      4
length       100    122    87    94    115
breadth       97     98    99   100    101
periemeter   394    440   372   388    432
area        9700  11956  8613  9400  11615

In [86]:
data.values.T

array([[  100,   122,    87,    94,   115],
       [   97,    98,    99,   100,   101],
       [  394,   440,   372,   388,   432],
       [ 9700, 11956,  8613,  9400, 11615]])

In [87]:
data

length  breadth  periemeter   area
0     100       97         394   9700
1     122       98         440  11956
2      87       99         372   8613
3      94      100         388   9400
4     115      101         432  11615

In [88]:
# accessing the first row of the matrix data
data.values[0]

array([ 100,   97,  394, 9700])

In [89]:
# to check the dimension of the data
data.ndim

2

### data selection in Data Frame

In [90]:
data

length  breadth  periemeter   area
0     100       97         394   9700
1     122       98         440  11956
2      87       99         372   8613
3      94      100         388   9400
4     115      101         432  11615

In [91]:
data.iloc[:2, :2] ## implicit indexing  iloc[rows, coumns]

length  breadth
0     100       97
1     122       98

In [92]:
# lets access 11615 of the area column using implicit indexing
data.iloc[4,3]

11615

In [93]:
data.loc[0, 'area'] ## expicit indexing loc[rows, columns]

9700

In [94]:
# lets access 11615 of the area column using explicit indexing
data.loc[4,'area']

11615

#### In the loc indexer we can combine masking and fancy indexing

In [95]:
data.head()

length  breadth  periemeter   area
0     100       97         394   9700
1     122       98         440  11956
2      87       99         372   8613
3      94      100         388   9400
4     115      101         432  11615

In [96]:
#lets select the data containing length less than 100 
mask = data.length < 100
data.loc[mask]

length  breadth  periemeter  area
2      87       99         372  8613
3      94      100         388  9400

In [97]:
# fany indexing 
data.loc[[0,1,4],['length','area']]

length   area
0     100   9700
1     122  11956
4     115  11615

In [98]:
# modifying the value 101 of breadth by 100
data.loc[4,'breadth'] = 1910

In [99]:
data

length  breadth  periemeter   area
0     100       97         394   9700
1     122       98         440  11956
2      87       99         372   8613
3      94      100         388   9400
4     115     1910         432  11615

## Index Alignment

In [100]:
a = pd.Series({'a':4,'b':5,'c':10},name = 'a')
b = pd.Series({'a':55,'c':55,'d':100},name = 'b')

In [101]:
a/b

a    0.072727
b         NaN
c    0.181818
d         NaN
dtype: float64

In [102]:
# to get rid of nan value we can use 
a.add(b, fill_value = 0) # here nan value is replaced by 0

a     59.0
b      5.0
c     65.0
d    100.0
dtype: float64

In [103]:
a.divide(b, fill_value = 1)

a    0.072727
b    5.000000
c    0.181818
d    0.010000
dtype: float64

In [104]:
#Index alignment in DataFrame
a = pd.DataFrame({'a':[4,5,6],'b':[1,4,6]},index = [1,3,5])
b = pd.DataFrame({'a':[4,7,9],'d':[4,8,1]},index = [1,2,3])

In [105]:
a


a  b
1  4  1
3  5  4
5  6  6

In [106]:
b

a  d
1  4  4
2  7  8
3  9  1

In [107]:
a + b

a   b   d
1   8.0 NaN NaN
2   NaN NaN NaN
3  14.0 NaN NaN
5   NaN NaN NaN

In [108]:
a.add(b, fill_value = 6)

a     b     d
1   8.0   7.0  10.0
2  13.0   NaN  14.0
3  14.0  10.0   7.0
5  12.0  12.0   NaN

### methods in pandas
##### +  add()
##### -  sub() , subtract()
#### *   mul() , multiply()

/ truediv() , div() , divide()

// floordiv()

% mod()

** pow()

## Handling Missing Data In Pandas

### Operating on Null Values

isnull()
Generate a Boolean mask indicating missing values

notnull()
Opposite of isnull()

dropna()
Return a filtered version of the data

fillna()
Return a copy of the data with missing values filled or imputed

##### Detecting null values

In [109]:
series = pd.Series([1,2,None, np.nan, 5, 7])

In [110]:
series

0    1.0
1    2.0
2    NaN
3    NaN
4    5.0
5    7.0
dtype: float64

In [111]:
series.isnull() # returns boolean mask of null value

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [112]:
series.notnull() # returns bollean mask of not null values

0     True
1     True
2    False
3    False
4     True
5     True
dtype: bool

In [113]:
# to count the sum of null value 
series.isnull().sum()

2

In [114]:
# boolean maskin using isnull()
series[series.notnull()]

0    1.0
1    2.0
4    5.0
5    7.0
dtype: float64

### Dropping null values

In [115]:
series

0    1.0
1    2.0
2    NaN
3    NaN
4    5.0
5    7.0
dtype: float64

In [116]:
series.dropna( axis = 'rows', inplace = False) # axis columns cannot be used

0    1.0
1    2.0
4    5.0
5    7.0
dtype: float64

In [117]:
# for data Frame we can use axis as columns or rows  
data = pd.DataFrame({'a': [1,2,3,4,np.nan], 'b':[np.nan, 3,5,6,2], 'c': [1,2,np.nan, 9 , 0]})

In [118]:
data.index = np.arange(1,6)

In [119]:
data.head()

a    b    c
1  1.0  NaN  1.0
2  2.0  3.0  2.0
3  3.0  5.0  NaN
4  4.0  6.0  9.0
5  NaN  2.0  0.0

In [120]:
# by default dropna() will drop all the rows containing null values

In [121]:
data.dropna(axis = 0, inplace = False) # drops all the rows containing nan values

a    b    c
2  2.0  3.0  2.0
4  4.0  6.0  9.0

In [122]:
data.dropna(axis = 1, inplace = False) # drops all the columns containing nan values

Empty DataFrame
Columns: []
Index: [1, 2, 3, 4, 5]

The default is how='any' , such that any row or column (depending on the axis key‐
word) containing a null value will be dropped. You can also specify how='all' , which
will only drop rows/columns that are all null values:


however there is a parameter called thresh ----   Require that many non-NA values in the rows or columns.

In [123]:
data = pd.DataFrame({'a': [1,4,3,4,np.nan], 'b':[np.nan, 3,5,np.nan,5], 'c': [1,2,np.nan, 9 , np.nan]})

In [124]:
data

a    b    c
0  1.0  NaN  1.0
1  4.0  3.0  2.0
2  3.0  5.0  NaN
3  4.0  NaN  9.0
4  NaN  5.0  NaN

In [125]:
# lets drop the rows containing more than 1 nan values
data.dropna(axis = 0, inplace = False, thresh = 2) # means rows must contain at least 2 non-na value 

a    b    c
0  1.0  NaN  1.0
1  4.0  3.0  2.0
2  3.0  5.0  NaN
3  4.0  NaN  9.0

In [126]:
# lets drop all the columns containing two nan vales
data.dropna(axis = 1, inplace = False , thresh = 2)

a    b    c
0  1.0  NaN  1.0
1  4.0  3.0  2.0
2  3.0  5.0  NaN
3  4.0  NaN  9.0
4  NaN  5.0  NaN

In [127]:
# lets drop the rows containing 2 nan values
thresh_value = data.shape[1] - 1 # here 1 is the number of null value we want in our data
data.dropna(axis = 0, inplace = False, thresh = 2)

a    b    c
0  1.0  NaN  1.0
1  4.0  3.0  2.0
2  3.0  5.0  NaN
3  4.0  NaN  9.0

### Filling null values

In [128]:
data

a    b    c
0  1.0  NaN  1.0
1  4.0  3.0  2.0
2  3.0  5.0  NaN
3  4.0  NaN  9.0
4  NaN  5.0  NaN

In [129]:
# lets fill the NaN value of column a with 3
data['a'].fillna(3,inplace = True)


In [130]:
# lets fill the Nan value of first row with 44
data.loc[0].fillna(44, inplace = True)

In [131]:
data

a     b    c
0  1.0  44.0  1.0
1  4.0   3.0  2.0
2  3.0   5.0  NaN
3  4.0   NaN  9.0
4  3.0   5.0  NaN

##### Methods of filling NaN values

In [132]:
# forward fill
data.iloc[:,2].fillna(method = 'ffill') # fill the nan value by the above data

0    1.0
1    2.0
2    2.0
3    9.0
4    9.0
Name: c, dtype: float64

In [133]:
# backward fill
data.loc[:,'b'].fillna(method = 'bfill') # fill the nan value by the below data

0    44.0
1     3.0
2     5.0
3     5.0
4     5.0
Name: b, dtype: float64

In [134]:
# forward fill doesnot work if the first element of the column contains nan value and the case is similar for
# backward fill if the last data is nan
data

a     b    c
0  1.0  44.0  1.0
1  4.0   3.0  2.0
2  3.0   5.0  NaN
3  4.0   NaN  9.0
4  3.0   5.0  NaN

In [135]:
#specifyind axis for ffill and bfill
data.fillna(method = 'ffill', axis = 0)

a     b    c
0  1.0  44.0  1.0
1  4.0   3.0  2.0
2  3.0   5.0  2.0
3  4.0   5.0  9.0
4  3.0   5.0  9.0

In [136]:
data

a     b    c
0  1.0  44.0  1.0
1  4.0   3.0  2.0
2  3.0   5.0  NaN
3  4.0   NaN  9.0
4  3.0   5.0  NaN

In [137]:
data.fillna(method = 'ffill', axis = 1)

a     b    c
0  1.0  44.0  1.0
1  4.0   3.0  2.0
2  3.0   5.0  5.0
3  4.0   4.0  9.0
4  3.0   5.0  5.0

In [138]:
data

a     b    c
0  1.0  44.0  1.0
1  4.0   3.0  2.0
2  3.0   5.0  NaN
3  4.0   NaN  9.0
4  3.0   5.0  NaN

In [139]:
data.fillna(method = 'bfill', axis = 1)

a     b    c
0  1.0  44.0  1.0
1  4.0   3.0  2.0
2  3.0   5.0  NaN
3  4.0   9.0  9.0
4  3.0   5.0  NaN

# Combining Datasets: Concat and Append

In [140]:
# series concatination 
a = pd.Series([1,2,3,4,5], index= list('abcde'))
b = pd.Series(np.arange(6,11), index = list('fghij'))
print(a, b)

a    1
b    2
c    3
d    4
e    5
dtype: int64 f     6
g     7
h     8
i     9
j    10
dtype: int64


In [141]:
#concatination
pd.concat([a,b], axis = 1, sort = True, ignore_index = False) # column wise concatination

0     1
a  1.0   NaN
b  2.0   NaN
c  3.0   NaN
d  4.0   NaN
e  5.0   NaN
f  NaN   6.0
g  NaN   7.0
h  NaN   8.0
i  NaN   9.0
j  NaN  10.0

In [142]:
pd.concat([a,b], sort = False, axis = 0, ignore_index= True)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

##### The append() method

In [143]:
data1 = pd.DataFrame({'a': np.arange(5), 'b': np.arange(5) * 3})
data2 = pd.DataFrame({'b': np.arange(5)+5, 'd': np.arange(5) *2})

In [144]:
data1

a   b
0  0   0
1  1   3
2  2   6
3  3   9
4  4  12

In [145]:
data2

b  d
0  5  0
1  6  2
2  7  4
3  8  6
4  9  8

In [146]:
data3 = data1.append(data2, sort = False, ignore_index = True )

In [147]:
data3.head()

a   b   d
0  0.0   0 NaN
1  1.0   3 NaN
2  2.0   6 NaN
3  3.0   9 NaN
4  4.0  12 NaN

# Combining Datasets Merge and join

In [148]:
data1 


a   b
0  0   0
1  1   3
2  2   6
3  3   9
4  4  12

In [149]:
data2.columns = ['b','c']
data2

b  c
0  5  0
1  6  2
2  7  4
3  8  6
4  9  8

In [150]:
data4 = pd.merge(data2, data1, sort = True)

In [151]:
data4.head()

b  c  a
0  6  2  2
1  9  8  3

At times you may wish to merge two datasets with different column names; for exam‐
ple, we may have a dataset in which the employee name is labeled as “name” rather
than “employee”. In this case, we can use the left_on and right_on keywords to
specify the two column names:

In [152]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})

In [153]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'salary': [70000, 80000, 120000, 90000]})

In [154]:
df1 

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [155]:
df3

name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [156]:
data3 = pd.merge(df1, df3, left_on = 'employee', right_on = 'name')

In [157]:
data3

employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [158]:
data3.drop('employee',axis = 1, inplace = True)

In [159]:
data3

group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000

###### join

In [160]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [161]:
df2 = df3.copy()

In [162]:
df2

name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [163]:
df1.join(df2, how = 'right')

employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [164]:
data1 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
'food': ['fish', 'beans', 'bread']},
columns=['name', 'food'])
data2 = pd.DataFrame({'name': ['Mary', 'Joseph'],
'drink': ['wine', 'beer']},
columns=['name', 'drink'])

In [165]:
data1

name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

In [166]:
data2

name drink
0    Mary  wine
1  Joseph  beer

Here we have merged two datasets that have only a single “name” entry in common:
Mary. By default, the result contains the intersection of the two sets of inputs; this is
what is known as an inner join.

In [167]:
pd.merge(data1, data2 ) 

name   food drink
0  Mary  bread  wine

In [169]:
pd.merge(data1, data2, how = 'outer' )

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

# Aggregation and Grouping

In [181]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))

In [182]:
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [183]:
ser.sum()

2.811925491708157

In [184]:
df = pd.DataFrame({'A': rng.rand(5),
'B': rng.rand(5)})

In [185]:
df

A         B
0  0.155995  0.020584
1  0.058084  0.969910
2  0.866176  0.832443
3  0.601115  0.212339
4  0.708073  0.181825

In [186]:
df.mean()

A    0.477888
B    0.443420
dtype: float64

In [191]:
df.mean(axis = 'columns')

0    0.088290
1    0.513997
2    0.849309
3    0.406727
4    0.444949
dtype: float64

#### GroupBy: Split, Apply, Combine
• The split step involves breaking up and grouping a DataFrame depending on the
value of the specified key.

• The apply step involves computing some function, usually an aggregate, transfor‐
mation, or filtering, within the individual groups.

• The combine step merges the results of these operations into an output array.

In [192]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
'data': range(6)}, columns=['key', 'data'])

In [194]:
df.head(7)

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [199]:
#We can compute the most basic split-apply-combine operation with the groupby() method of DataFrame 
group = df.groupby(by = 'key')

In [203]:
for keys, values in group:
    print(keys, values)

A   key  data
0   A     0
3   A     3
B   key  data
1   B     1
4   B     4
C   key  data
2   C     2
5   C     5


## Aggregration functions of pandas

first() , last() First and last item

count( ) , count total number of item

mean() , median() Mean and median

min() , max() Minimum and maximum

std() , var() Standard deviation and variance

mad() Mean absolute deviation

prod() Product of all items

sum() Sum of all items




In [204]:
group.sum()

data
key      
A       3
B       5
C       7

In [205]:
group.count()

data
key      
A       2
B       2
C       2

In [206]:
group.max()

data
key      
A       3
B       4
C       5

In [207]:
group.min()

data
key      
A       0
B       1
C       2

In [210]:
group.describe()

data                                         
    count mean      std  min   25%  50%   75%  max
key                                               
A     2.0  1.5  2.12132  0.0  0.75  1.5  2.25  3.0
B     2.0  2.5  2.12132  1.0  1.75  2.5  3.25  4.0
C     2.0  3.5  2.12132  2.0  2.75  3.5  4.25  5.0

#### Aggregate, filter, transform, apply

In [211]:
rng = np.random.RandomState(0)
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
'data1': range(6),
'data2': rng.randint(0, 10, 6)})

In [212]:
df

key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

##### Aggregate
It can take
a string, a function, or a list , and compute all the aggregates at once

In [218]:
df.groupby('key').aggregate(['min', np.median, max])

data1            data2           
      min median max   min median max
key                                  
A       0    1.5   3     3    4.0   5
B       1    2.5   4     0    3.5   7
C       2    3.5   5     3    6.0   9

In [220]:
df.groupby('key').aggregate({'data1': min,'data2': max})

data1  data2
key              
A        0      5
B        1      7
C        2      9

### Filter
A filtering operation allows you to drop data based on the group proper‐
ties.

In [223]:
def filter_func(x):
    return x['data2'].std() > 4

df.groupby('key').std()

data1     data2
key                   
A    2.12132  1.414214
B    2.12132  4.949747
C    2.12132  4.242641

In [227]:
'''The filter() function should return a Boolean value specifying whether the group
passes the filtering. Here because group A does not have a standard deviation greater
than 4, it is dropped from the result.'''
df.groupby('key').filter(filter_func)


key  data1  data2
1   B      1      0
2   C      2      3
4   B      4      7
5   C      5      9

### Transformation. 
While aggregation must return a reduced version of the data, trans‐
formation can return some transformed version of the full data to recombine.

In [232]:
df.groupby('key').transform(lambda x: x - x.median())

data1  data2
0   -1.5    1.0
1   -1.5   -3.5
2   -1.5   -3.0
3    1.5   -1.0
4    1.5    3.5
5    1.5    3.0

In [233]:
df

key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

## Apply

The apply() method lets you apply an arbitrary function to the
group results.

In [238]:
def norm_by_data2(x):
        # x is a DataFrame of group values
        x['data1'] /= x['data2'].sum()
        return x
df

key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

In [237]:
print(df.groupby('key').apply(norm_by_data2))

  key     data1  data2
0   A  0.000000      5
1   B  0.142857      0
2   C  0.166667      3
3   A  0.375000      3
4   B  0.571429      7
5   C  0.416667      9
